# Site settings
title: Agile Transformation
description: Agile Transformation > Warum die Daten für sich sprechen - Ein datengetriebener Blick auf den Erfolg agiler Arbeitsweisen.

# Theme settings (THIS IS CRUCIAL FOR GITHUB PAGES)
# Using 'remote_theme' to tell GitHub Pages to fetch Just the Docs from its repo
remote_theme: just-the-docs/just-the-docs@v0.6.0 # Verwende eine spezifische Version für Stabilität

# Just the Docs specific configurations (optional, siehe Theme-Doku)
color_scheme: light
search_enabled: true
nav_external_links: true
footer_custom: "bestes theme ever"

# Jekyll build settings
# Exclude files/folders that Jekyll should ignore during the build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules # If you ever use npm/yarn
  - .git # Exclude the git folder itself
  - .gitignore
  - README.md # If you have a separate README for your repo